"""Add analysis fields to recordings table

Revision ID: c5aa6908da59
Revises: 
Create Date: 2025-06-22 14:04:18.205371

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c5aa6908da59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new analysis fields to recordings table
    op.add_column('recordings', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('recordings', sa.Column('action_items', sa.JSON(), nullable=True))
    op.add_column('recordings', sa.Column('decisions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove analysis fields from recordings table
    op.drop_column('recordings', 'decisions')
    op.drop_column('recordings', 'action_items')
    op.drop_column('recordings', 'summary')
    # ### end Alembic commands ### 