"""add_visual_summary_url_to_recordings

Revision ID: 8b42cfd214f3
Revises: c5aa6908da59
Create Date: 2025-06-22 16:37:33.642088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b42cfd214f3'
down_revision = 'c5aa6908da59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recordings', sa.Column('visual_summary_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recordings', 'visual_summary_url')
    # ### end Alembic commands ### 