"""create_labeling_rules_table

Revision ID: d48136932e87
Revises: 9f3169da380a
Create Date: 2025-06-26 16:57:46.641977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd48136932e87'
down_revision = '9f3169da380a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labeling_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label_name', sa.String(length=100), nullable=False),
    sa.Column('label_color', sa.String(length=7), nullable=False),
    sa.Column('rule_description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labeling_rules_id'), 'labeling_rules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_labeling_rules_id'), table_name='labeling_rules')
    op.drop_table('labeling_rules')
    # ### end Alembic commands ### 