"""add_labeling_rules_and_recording_labels

Revision ID: 9f3169da380a
Revises: 8b42cfd214f3
Create Date: 2025-06-26 16:53:41.069941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f3169da380a'
down_revision = '8b42cfd214f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recordings', sa.Column('labels', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recordings', 'labels')
    # ### end Alembic commands ### 